### ISSUE TITLE
build live-kde-apps with stable release of KF5

### ISSUE THREAD

**Issue by ff2000** [gentoo/kde#189]
I currently would like to have dolphin + cantor built from git (switch to KF5). Unfortunately the eclasses force the whole dependencies to be built from git, too. Dolphin requires KF5 >= 5.7.0, cantor doesn't put any constraints on a minimum version of KF5. I actually built both with KF5-5.8.0 without any issues.

Could we simply rely on specified "FRAMEWORKS_MINIMAL/ECM_MINIMAL/..." versions in the ebuild, especially on live ones? I could come up with a PR if you think it's worth it.

**Comment by kensington** [comment]
We've switched this backwards and forwards a few times now - everytime we change, some complains about the unnecessary dependency or build failure.

Specifying the required versions in each ebuild is the most technically correct solution, but in reality nobody will maintain it and it will become outdated quickly.

Perhaps as a compromise, we could limit the dependencies to kde-plasma/*? IIRC it's what prompted the live requirement originally since development was moving so fast.

**Comment by ff2000** [comment]
I think most users are happy with the current state. So I simply will setup an environment in $HOME to build and run kde applications. (cantor anyway needs a patch to fix building python backend with both py2 and py3 available)
If you think limiting live deps to only plasma works without too much additional work this of course would be great.

**Comment by kensington** [comment]
This appears to have since been fixed in 0dfcd95ad90d7dd57d33447ff075b4b0ebf1cbb2, so only frameworks/plasma-9999 needs live frameworks.
